//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMETRO.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFMETRO.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Text Color.
        /// </summary>
        public static string AccentTextColor {
            get {
                return ResourceManager.GetString("AccentTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add From Text File.
        /// </summary>
        public static string AddFromTextFile {
            get {
                return ResourceManager.GetString("AddFromTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subtitles.
        /// </summary>
        public static string AddSubtitles {
            get {
                return ResourceManager.GetString("AddSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string AddToQueue {
            get {
                return ResourceManager.GetString("AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert on Finish.
        /// </summary>
        public static string AlertOnFinish {
            get {
                return ResourceManager.GetString("AlertOnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has already been downloaded under this file name.
        /// </summary>
        public static string AlreadyDownloaded {
            get {
                return ResourceManager.GetString("AlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version detected. Would you like to update? .
        /// </summary>
        public static string AskToUpdateGUI {
            get {
                return ResourceManager.GetString("AskToUpdateGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of youtube-dl detected. Would you like to update? For that, the program needs to restart and the process might take several minutes..
        /// </summary>
        public static string AskToUpdateYoutubeDL {
            get {
                return ResourceManager.GetString("AskToUpdateYoutubeDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted From:.
        /// </summary>
        public static string ConvertedFrom {
            get {
                return ResourceManager.GetString("ConvertedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted To:.
        /// </summary>
        public static string ConvertedTo {
            get {
                return ResourceManager.GetString("ConvertedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to converter.
        /// </summary>
        public static string Converter {
            get {
                return ResourceManager.GetString("Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop From:.
        /// </summary>
        public static string CropFrom {
            get {
                return ResourceManager.GetString("CropFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: .
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string DownloadLocation {
            get {
                return ResourceManager.GetString("DownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Queue.
        /// </summary>
        public static string ExportQueue {
            get {
                return ResourceManager.GetString("ExportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        public static string FFMpeg {
            get {
                return ResourceManager.GetString("FFMpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Overwrite?.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filetype.
        /// </summary>
        public static string Filetype {
            get {
                return ResourceManager.GetString("Filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads completed!.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Style.
        /// </summary>
        public static string GeneralStyle {
            get {
                return ResourceManager.GetString("GeneralStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Title....
        /// </summary>
        public static string GettingTitle {
            get {
                return ResourceManager.GetString("GettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download video! This filetype may not be available at the moment. Try using the default filetype!.
        /// </summary>
        public static string InvalidFiletype {
            get {
                return ResourceManager.GetString("InvalidFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path selected! Select a valid path and try again!.
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL! This video might not be available for download or doesn&apos;t exist.
        /// </summary>
        public static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video!.
        /// </summary>
        public static string InvalidVideo {
            get {
                return ResourceManager.GetString("InvalidVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Videos.
        /// </summary>
        public static string JoinVideos {
            get {
                return ResourceManager.GetString("JoinVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Audio and Video.
        /// </summary>
        public static string MergeAV {
            get {
                return ResourceManager.GetString("MergeAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version: .
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conversion.
        /// </summary>
        public static string NoConversion {
            get {
                return ResourceManager.GetString("NoConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Download.
        /// </summary>
        public static string NoDownload {
            get {
                return ResourceManager.GetString("NoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original File:.
        /// </summary>
        public static string OriginalFile {
            get {
                return ResourceManager.GetString("OriginalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other:.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File:.
        /// </summary>
        public static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot choose the same name and extension as the original file. Please pick another name..
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file format.
        /// </summary>
        public static string PleaseSelectFormat {
            get {
                return ResourceManager.GetString("PleaseSelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize Playlists Over Videos.
        /// </summary>
        public static string PrioritizePlaylists {
            get {
                return ResourceManager.GetString("PrioritizePlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Configurations.
        /// </summary>
        public static string ResetConfig {
            get {
                return ResourceManager.GetString("ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred while resetting the configuration file. Do you have the necessary permissions to access the file?.
        /// </summary>
        public static string ResetError {
            get {
                return ResourceManager.GetString("ResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the program to apply language changes.
        /// </summary>
        public static string RestartChanges {
            get {
                return ResourceManager.GetString("RestartChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Formats....
        /// </summary>
        public static string RetrevingFormats {
            get {
                return ResourceManager.GetString("RetrevingFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destination.
        /// </summary>
        public static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Video.
        /// </summary>
        public static string SelectVideo {
            get {
                return ResourceManager.GetString("SelectVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snag Frame Every.
        /// </summary>
        public static string SnagEvery {
            get {
                return ResourceManager.GetString("SnagEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Up....
        /// </summary>
        public static string StartingUp {
            get {
                return ResourceManager.GetString("StartingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To End of Video.
        /// </summary>
        public static string ToEnd {
            get {
                return ResourceManager.GetString("ToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to gather video title!.
        /// </summary>
        public static string UnableGatherTitle {
            get {
                return ResourceManager.GetString("UnableGatherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update; program was not given permission to modify files in installation folder.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating youtube-dl....
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Custom Locale.
        /// </summary>
        public static string UseCustomLocale {
            get {
                return ResourceManager.GetString("UseCustomLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Verbose Status.
        /// </summary>
        public static string UseVerboseStatus {
            get {
                return ResourceManager.GetString("UseVerboseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Video Title.
        /// </summary>
        public static string UseVideoTitle {
            get {
                return ResourceManager.GetString("UseVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Title.
        /// </summary>
        public static string VideoTitle {
            get {
                return ResourceManager.GetString("VideoTitle", resourceCulture);
            }
        }
    }
}
